const restaurants=[{id:1,name:"Valley Cafe",emoji:"🍔",tag:"Local favorites",desc:"Breakfast, burgers & comfort food",open:true,items:[["Classic Burger",12],["Breakfast Plate",11],["Chicken Basket",13],["Iced Coffee",5]]},{id:2,name:"More Hoopa restaurants",emoji:"🌮",tag:"Coming soon",desc:"Restaurants can join Hoopa Eats and manage their own menu.",open:false,items:[]}];
let cart={},orders=JSON.parse(localStorage.getItem("heOrders")||"[]");
function render(){document.getElementById("app").innerHTML='<section class="hero"><h1>What are you craving?</h1><input class="search" placeholder="Search restaurants or food" oninput="filterFeed(this.value)"><div class="tabs"><button class="pill">All</button><button class="pill">Breakfast</button><button class="pill">Lunch</button><button class="pill">Dinner</button><button class="pill">Specials</button></div></section><div id="feed">'+restaurants.map(card).join("")+'</div>'}
function card(r){return '<article class="card restaurant" data-search="'+(r.name+" "+r.tag+" "+r.desc).toLowerCase()+'" onclick="openRestaurant('+r.id+')"><div class="food">'+r.emoji+'</div><div class="content"><div class="row"><div><b>'+r.name+'</b><div class="muted">'+r.desc+'</div></div><span>'+(r.open?"Open":"Coming soon")+'</span></div></div></article>'}
function filterFeed(q){q=q.toLowerCase();document.querySelectorAll(".restaurant").forEach(x=>x.style.display=x.dataset.search.includes(q)?"":"none")}
function openRestaurant(id){let r=restaurants.find(x=>x.id===id);let m='<h2>'+r.name+'</h2><p class="muted">'+r.desc+'</p>';if(!r.items.length)m+='<div class="status">This restaurant has not joined yet.</div>';else m+=r.items.map((x,i)=>'<div class="menuitem row"><div><b>'+x[0]+'</b><div>$'+x[1].toFixed(2)+'</div></div><div class="qty"><button onclick="changeQty('+id+','+i+',-1)">−</button><b id="q'+id+'-'+i+'">'+(cart[id+"-"+i]||0)+'</b><button onclick="changeQty('+id+','+i+',1)">+</button></div></div>').join("")+'<button class="btn" style="width:100%;margin-top:18px" onclick="checkout('+id+')">Place Order</button>';show(m)}
function changeQty(r,i,d){let k=r+"-"+i;cart[k]=Math.max(0,(cart[k]||0)+d);document.getElementById("q"+k).textContent=cart[k]}
function checkout(id){let r=restaurants.find(x=>x.id===id),lines=[],total=0;r.items.forEach((x,i)=>{let q=cart[id+"-"+i]||0;if(q){lines.push(q+" × "+x[0]);total+=q*x[1]}});if(!lines.length)return alert("Add something to your order first.");show('<h2>Checkout</h2><p>'+lines.join("<br>")+'</p><h3>Total: $'+total.toFixed(2)+'</h3><label>Name for pickup</label><input id="pickup" class="search" placeholder="Your name"><p class="muted">Payment processing will be connected before public launch. This build does not collect card numbers.</p><button class="btn" style="width:100%" onclick="submitOrder('+id+','+total+')">Submit test order</button>')}
function submitOrder(id,total){let name=document.getElementById("pickup").value.trim();if(!name)return alert("Enter a pickup name.");let o={id:Date.now(),restaurant:id,name,total,status:"Received",time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})};orders.unshift(o);localStorage.setItem("heOrders",JSON.stringify(orders));cart={};show('<h2>Order received ✓</h2><div class="status"><b>#'+String(o.id).slice(-4)+'</b><br>Status: '+o.status+'<br>Pickup name: '+o.name+'</div><p>This order is saved on this device while we connect the production database.</p>')}
function toggleProfile(){show('<h2>Hoopa Eats</h2><button class="btn secondary" style="width:100%" onclick="showOrders()">My orders</button><hr><h3>Restaurant owners</h3><p class="muted">Business login and dashboard are being connected to the production database.</p>')}
function showOrders(){show('<h2>My orders</h2>'+(orders.length?orders.map(o=>'<div class="status"><b>#'+String(o.id).slice(-4)+'</b> · '+o.name+'<br>'+o.status+' · $'+o.total.toFixed(2)+'</div>').join(""):'<p>No orders yet.</p>'))}
function openChat(){show('<h2>Restaurant messages</h2><p>When a restaurant joins, customers will be able to message that restaurant here.</p>')}
function show(h){document.getElementById("modalBody").innerHTML=h;document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}function goHome(){closeModal();window.scrollTo({top:0,behavior:"smooth"})}render();