const SUPABASE_URL="https://uyexhphgnbngsscgbadh.supabase.co";
const SUPABASE_KEY="sb_publishable_SUGwEIXnaabCXYC0eU8MCQ_43AzhU_z";
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let restaurants=[],cart={};
const HOOPA_DIRECTORY=[
 {id:"directory-valley-cafe",name:"The Valley Cafe",description:"American restaurant, burgers, chicken sandwiches, club sandwiches, wraps, fries, milkshakes, lunch, dinner, comfort food",phone:"(530) 922-0825",address:"12676 Highway 96, Hoopa, CA 95546",is_directory:true},
 {id:"directory-gals-firepit",name:"Gal's Firepit Pizza",description:"Pizza food truck, wood-fired pizza, Hawaiian pizza, meat pizza, pesto pizza, vegetarian pizza, dinner, takeaway",phone:"(530) 716-0682",address:"11716 CA-96, Hoopa, CA 95546",is_directory:true},
 {id:"directory-cup-of-joe",name:"Cup Of Joe",description:"Coffee, cafe, espresso, hot drinks, cold drinks, breakfast, lunch, quick bites",phone:"(530) 625-5004",address:"12651 CA-96, Hoopa, CA 95546",is_directory:true},
 {id:"directory-burger-barn",name:"Burger Barn",description:"Burgers, cheeseburgers, sandwiches, American food, lunch, quick bites",phone:"(530) 625-9100",address:"Highway 96, Hoopa, CA 95546",is_directory:true},
 {id:"directory-hoopa-shopping",name:"Hoopa Shopping Center | iłwai kiliwh",description:"Full deli, hot food, sandwiches, fried chicken, chicken strips, pizza sticks, JoJos, espresso bar, coffee, groceries, prepared food",phone:"(530) 625-1013",address:"12500 State Hwy 96, Hoopa, CA 95546",is_directory:true},
 {id:"directory-hoopa-mini-mart",name:"Hoopa Mini-Mart Gas Station",description:"Convenience food, snacks, drinks, fruit, vegetables, meat, groceries, quick bites",phone:"(530) 625-4341",address:"12591 CA-96, Hoopa, CA 95546",is_directory:true},
 {id:"directory-mf-craving",name:"MF Craving",description:"Food trailer, local food, meals, snacks, quick bites",phone:"(707) 599-9365",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-gatos-tacos",name:"Gato's Tacos",description:"Tacos, Mexican food, food trailer, Mexican, lunch, dinner, quick bites",phone:"(707) 474-1091",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-joseph-girls",name:"Joseph Girls / Cali Kitchen",description:"Food sales, local food, meals, snacks, kitchen",phone:"(707) 613-9361",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-tribal-treats",name:"Tribal Treats and Catering",description:"Catering, treats, local food, desserts, meals, food business",phone:"(530) 784-3048",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-marias-tacos",name:"Maria's Tacos",description:"Tacos, Mexican food, Mexican, local food, lunch, dinner, quick bites",phone:"(530) 610-5397",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-snacky-lews",name:"Snacky Lews",description:"Snacks, local food, treats, quick bites, food business",phone:"(707) 497-8489",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-kinsinta-korner",name:"Kinsinta Korner",description:"Local food, snacks, meals, quick bites, food business",phone:"(707) 672-2165",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-udbies",name:"Udbie's Food & Sweets",description:"Sweets, desserts, snacks, local food, treats, food business",phone:"(530) 610-8541",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-micks",name:"Mick's Chick's & More",description:"Baked goods, eggs, candy, sweets, desserts, local food",phone:"(707) 499-8410",address:"Hoopa, CA 95546",is_directory:true},
 {id:"directory-smokerz",name:"Smoker'z BBQ and Catering",description:"BBQ, barbecue, smoked meat, catering, local food, lunch, dinner",phone:"(707) 601-8502",address:"Hoopa, CA 95546",is_directory:true}
]
const feed=document.querySelector("#feed"),sheet=document.querySelector("#sheet"),inside=document.querySelector("#inside");
const money=n=>"$"+Number(n||0).toFixed(2);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function refreshDashboardTab(){}
async function myRestaurant(){const {data:{user}}=await db.auth.getUser();if(!user)return profile();const {data:r,error}=await db.from("restaurants").select("*").eq("owner_id",user.id).maybeSingle();if(error)return alert(error.message);if(!r)return ownerDashboard();ownerRestaurant=r;restaurantProfile()}

function restaurantProfile(){const r=ownerRestaurant;if(!r)return ownerDashboard();inside.innerHTML='<div class="restaurant-public-editor"><div class="restaurant-profile-head"><div class="profile-logo">'+(r.image_url?'<img src="'+esc(r.image_url)+'" alt="">':'🏪')+'</div><div><h2>My Restaurant</h2><p class="muted">Control how your restaurant appears to customers on Hoopa Eats.</p></div></div><div class="profile-preview"><span>Customer profile preview</span><b>'+esc(r.name||"Your restaurant")+'</b><p>'+esc(r.description||"Add a short description so customers know what you serve.")+'</p></div><div class="profile-section"><h3>Public identity</h3><label>Restaurant name<input id="profileName" value="'+esc(r.name||"")+'" placeholder="Restaurant name"></label><label>Logo / profile image<input id="profileImage" value="'+esc(r.image_url||"")+'" placeholder="Paste image URL"></label><p class="field-help">This image appears with your restaurant listing. Direct image uploads are coming later.</p><label>Customer-facing description<textarea id="profileDescription" placeholder="What should customers know about your restaurant?">'+esc(r.description||"")+'</textarea></label></div><div class="profile-section"><h3>Public contact details</h3><p class="field-help">These details can be shown to customers. Account email and password stay in Settings.</p><label>Restaurant phone<input id="profilePhone" type="tel" value="'+esc(r.phone||"")+'" placeholder="Restaurant phone"></label><label>Restaurant address<input id="profileAddress" value="'+esc(r.address||"")+'" placeholder="Restaurant address"></label></div><button class="primary full" onclick="saveRestaurantProfile()">Save customer profile</button><button class="full" onclick="sheet.close()">Close</button></div>';sheet.showModal()}
async function saveRestaurantProfile(){const values={name:document.querySelector("#profileName").value.trim(),image_url:document.querySelector("#profileImage").value.trim()||null,description:document.querySelector("#profileDescription").value.trim(),phone:document.querySelector("#profilePhone").value.trim(),address:document.querySelector("#profileAddress").value.trim()};if(!values.name)return alert("Enter a restaurant name.");const {data,error}=await db.from("restaurants").update(values).eq("id",ownerRestaurant.id).select("*").single();if(error)return alert(error.message);ownerRestaurant=data;await loadRestaurants();restaurantProfile();alert("Restaurant profile saved.")}
async function siteSettings(){const {data:{user}}=await db.auth.getUser();if(!user)return profile();await ownerDashboard();accountSettings()}
async function openDashboardSection(tab){const {data:{user}}=await db.auth.getUser();if(!user)return profile();await ownerDashboard();ownerNavigate(tab)}
async function openDashboardTab(){const {data:{user}}=await db.auth.getUser();if(user)return ownerDashboard();profile()}
async function customerHome(){document.querySelector("#ownerApp").hidden=true;document.querySelector("#customerApp").hidden=false;await refreshDashboardTab();await refreshDashboardTab();loadRestaurants();scrollTo({top:0,behavior:"smooth"})}
async function loadRestaurants(){const {data,error}=await db.from("restaurants").select("*").order("created_at");if(error){console.error(error);feed.innerHTML='<p>Could not load restaurants.</p>';return}const live=data||[];const {data:items,error:menuError}=await db.from("menu_items").select("restaurant_id,name,description,category").eq("is_available",true);if(menuError)console.error(menuError);const menuByRestaurant={};(items||[]).forEach(x=>{(menuByRestaurant[x.restaurant_id]??=[]).push([x.name,x.description,x.category].filter(Boolean).join(" "))});const liveNames=new Set(live.map(r=>r.name.trim().toLowerCase()));const directory=HOOPA_DIRECTORY.filter(r=>!liveNames.has(r.name.trim().toLowerCase()));restaurants=[...live,...directory].map(r=>({...r,_searchText:[r.name,r.description,...(menuByRestaurant[r.id]||[])].filter(Boolean).join(" ").toLowerCase()}));draw()}
function draw(){feed.innerHTML=restaurants.length?restaurants.map(r=>'<article class="card restaurant" data-q="'+esc(r._searchText||(r.name+" "+(r.description||"")).toLowerCase())+'" onclick="restaurant(\''+r.id+'\')"><div class="food">🍽️</div><div class="pad row"><div><b>'+esc(r.name)+'</b><div class="muted">'+esc(r.description||"Local restaurant")+'</div></div><span>'+(!r.is_open?"Closed":r.accepting_orders?"Open":"Paused")+'</span></div></article>').join(""):'<article class="card"><div class="pad"><b>Hoopa Eats is getting ready</b><p class="muted">Restaurants will appear here as they join.</p></div></article>'}
function submitFoodSearch(event){event?.preventDefault();filterFood();document.querySelector("#search")?.blur()}
function filterFood(){const input=document.querySelector("#search"),q=(input?.value||"").trim().toLowerCase(),words=q.split(/\\s+/).filter(Boolean);document.querySelectorAll(".restaurant").forEach(x=>{const text=x.dataset.q||"";x.style.display=!words.length||words.every(w=>text.includes(w))?"":"none"});const visible=[...document.querySelectorAll(".restaurant")].filter(x=>x.style.display!=="none").length;let empty=document.querySelector("#searchEmpty");if(q&&!visible){if(!empty){empty=document.createElement("article");empty.id="searchEmpty";empty.className="card";feed.appendChild(empty)}empty.innerHTML='<div class="pad"><b>No matches found</b><p class="muted">Try a food like tacos, burgers, pizza, breakfast, or a cuisine like Mexican.</p></div>'}else empty?.remove()}
async function restaurant(id){const r=restaurants.find(x=>x.id===id);if(!r)return;if(r.is_directory){inside.innerHTML='<div class="directory-detail"><span class="directory-label">Hoopa food directory</span><h2>'+esc(r.name)+'</h2><p>'+esc(r.description||"Local food place")+'</p>'+(r.address?'<div class="hub-panel"><b>Address</b><p>'+esc(r.address)+'</p>'+(r.phone?'<b>Phone</b><p>'+esc(r.phone)+'</p>':'')+'</div>':'')+'<p class="muted">This place appears in Hoopa Eats search so customers can discover local food. Online ordering through Hoopa Eats is not connected for this listing yet.</p><button class="full" onclick="sheet.close()">Close</button></div>';sheet.showModal();return}inside.innerHTML='<h2>'+esc(r.name)+'</h2><p>Loading menu…</p>';sheet.showModal();const {data,error}=await db.from("menu_items").select("*").eq("restaurant_id",id).order("created_at");if(error)return inside.innerHTML='<h2>'+esc(r.name)+'</h2><p>Menu could not load.</p>';const items=data||[];inside.innerHTML='<h2>'+esc(r.name)+'</h2><p class="muted">'+esc(r.description||"")+'</p>'+(items.length?items.map(x=>'<div class="menu row"><div><b>'+esc(x.name)+'</b><br><span class="muted">'+esc(x.description||"")+'</span><br>'+money(x.price)+'</div><button '+(!x.is_available?'disabled':'')+' onclick="add(\\''+id+'\\',\\''+x.id+'\\',\\''+encodeURIComponent(x.name)+'\\','+Number(x.price)+')">'+(x.is_available?"Add":"Sold out")+'</button></div>').join("")+'<button class="primary full" onclick="checkout(\\''+id+'\\')">Place Order</button>':'<p>Menu coming soon.</p>')}
function add(rid,iid,name,price){if(!cart[iid])cart[iid]={restaurant_id:rid,menu_item_id:iid,name:decodeURIComponent(name),price:+price,quantity:0};cart[iid].quantity++;alert("Added to cart")}
function checkout(id){const r=restaurants.find(x=>x.id===id);if(!r.is_open||!r.accepting_orders)return alert("This restaurant is closed or has paused new orders.");const lines=Object.values(cart).filter(x=>x.restaurant_id===id);if(!lines.length)return alert("Add something first.");const total=lines.reduce((s,x)=>s+x.price*x.quantity,0),canPickup=r.offers_pickup!==false,canDelivery=r.offers_delivery===true;if(!canPickup&&!canDelivery)return alert("This restaurant is not accepting pickup or delivery right now.");inside.innerHTML='<h2>Checkout</h2>'+lines.map(x=>'<p>'+x.quantity+' × '+esc(x.name)+' — '+money(x.price*x.quantity)+'</p>').join("")+'<h3>Food subtotal: '+money(total)+'</h3><h3>How do you want your order?</h3>'+(canPickup?'<label><input type="radio" name="fulfillment" value="pickup" checked onchange="fulfillmentChanged()"> Pickup</label> ':'')+(canDelivery?'<label><input type="radio" name="fulfillment" value="delivery" '+(!canPickup?'checked':'')+' onchange="fulfillmentChanged()"> Delivery</label><p class="muted">Delivery fee: '+money(r.delivery_fee)+(Number(r.delivery_minimum)>0?' · Minimum '+money(r.delivery_minimum):'')+'</p>':'')+'<input id="pickup" placeholder="Name for order"><input id="phone" placeholder="Phone number (optional)"><div id="deliveryFields" style="display:none"><input id="deliveryAddress" placeholder="Delivery address"><textarea id="deliveryInstructions" placeholder="Delivery instructions (optional)"></textarea></div><p class="muted">Online payment is not connected yet. Do not enter card information.</p><button class="primary full" onclick="submitOrder(\''+id+'\')">Submit order</button>';fulfillmentChanged()}
function fulfillmentChanged(){const choice=document.querySelector('input[name="fulfillment"]:checked'),box=document.querySelector("#deliveryFields");if(box)box.style.display=choice&&choice.value==="delivery"?"block":"none"}
async function submitOrder(id){const name=pickup.value.trim();if(!name)return alert("Enter a name for the order.");const choice=document.querySelector('input[name="fulfillment"]:checked');if(!choice)return alert("Choose pickup or delivery.");const type=choice.value,address=document.querySelector("#deliveryAddress")?.value.trim()||null,instructions=document.querySelector("#deliveryInstructions")?.value.trim()||null;if(type==="delivery"&&!address)return alert("Enter a delivery address.");const lines=Object.values(cart).filter(x=>x.restaurant_id===id);if(!lines.length)return alert("Your cart is empty.");const button=inside.querySelector(".primary");if(button){button.disabled=true;button.textContent="Sending order…"}const {data:orderId,error}=await db.rpc("create_guest_order",{p_restaurant_id:id,p_customer_name:name,p_customer_phone:phone.value.trim()||null,p_customer_notes:null,p_items:lines.map(x=>({menu_item_id:x.menu_item_id,quantity:x.quantity})),p_fulfillment_type:type,p_delivery_address:address,p_delivery_instructions:instructions});if(error){console.error(error);if(button){button.disabled=false;button.textContent="Submit order"}return alert(error.message||"Order could not be submitted.")}lines.forEach(x=>delete cart[x.menu_item_id]);inside.innerHTML='<h2>Order received ✓</h2><p>Your '+type+' order was sent to the restaurant.</p><p class="muted">Order '+String(orderId).slice(0,8)+'</p>'}
async function profile(){const {data:{user}}=await db.auth.getUser();if(user)return ownerDashboard();inside.innerHTML='<h2>Restaurant owner</h2><p class="muted">Customers can order as guests. Restaurant owners log in here.</p><input id="email" type="email" placeholder="Business email"><input id="password" type="password" placeholder="Password"><button class="primary full" onclick="signIn()">Log in</button><button class="full" onclick="signUp()">Create restaurant account</button>';sheet.showModal()}
async function signIn(){const {error}=await db.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)return alert(error.message);ownerDashboard()}
async function signUp(){const {error}=await db.auth.signUp({email:email.value.trim(),password:password.value});if(error)return alert(error.message);inside.innerHTML='<h2>Check your email</h2><p>Confirm your email, then come back and log in.</p>'}
let ownerRestaurant=null,ownerOrders=[],ownerTab="dashboard",orderFilter="all",orderChannel=null,audioCtx=null;
async function ownerDashboard(){const {data:{user}}=await db.auth.getUser();if(!user)return profile();const {data:r,error}=await db.from("restaurants").select("*").eq("owner_id",user.id).maybeSingle();if(error)return alert(error.message);if(!r){inside.innerHTML='<h2>Restaurant setup</h2><input id="rname" placeholder="Restaurant name"><textarea id="rdesc" placeholder="Description"></textarea><button class="primary full" onclick="createRestaurant()">Create restaurant</button><button class="full" onclick="logout()">Log out</button>';sheet.showModal();return}ownerRestaurant=r;const {data:orders,error:oe}=await db.from("orders").select("*,order_items(id,item_name,quantity,unit_price)").eq("restaurant_id",r.id).order("created_at",{ascending:false}).limit(50);if(oe){console.error(oe);const fallback=await db.from("orders").select("*").eq("restaurant_id",r.id).order("created_at",{ascending:false}).limit(50);ownerOrders=fallback.data||[]}else ownerOrders=orders||[];sheet.close();document.querySelector("#customerApp").hidden=true;document.querySelector("#ownerApp").hidden=false;renderOwnerHub();startOrderRealtime(r.id)}
function startOrderRealtime(rid){if(orderChannel){db.removeChannel(orderChannel);orderChannel=null}orderChannel=db.channel("restaurant-orders-"+rid).on("postgres_changes",{event:"INSERT",schema:"public",table:"orders",filter:"restaurant_id=eq."+rid},async payload=>{await receiveRealtimeOrder(payload.new)}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"orders",filter:"restaurant_id=eq."+rid},async payload=>{const i=ownerOrders.findIndex(o=>o.id===payload.new.id);if(i>=0)ownerOrders[i]={...ownerOrders[i],...payload.new};renderOwnerHub()}).subscribe(status=>{console.log("Order realtime:",status)})}
async function receiveRealtimeOrder(row){if(ownerOrders.some(o=>o.id===row.id))return;const {data,error}=await db.from("orders").select("*,order_items(id,item_name,quantity,unit_price)").eq("id",row.id).single();const order=error?row:data;ownerOrders.unshift(order);renderOwnerHub();playOrderSound();showOrderToast(order)}
function enableOrderSound(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();playOrderSound(true);document.querySelector("#soundEnable")?.remove();localStorage.setItem("hoopaEatsSound","on")}catch(e){console.error(e)}}
function playOrderSound(test=false){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state!=="running"){if(!test)return}const now=audioCtx.currentTime;[0,0.18,0.36].forEach((delay,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type="sine";o.frequency.setValueAtTime(i===1?880:660,now+delay);g.gain.setValueAtTime(.0001,now+delay);g.gain.exponentialRampToValueAtTime(.22,now+delay+.02);g.gain.exponentialRampToValueAtTime(.0001,now+delay+.15);o.connect(g);g.connect(audioCtx.destination);o.start(now+delay);o.stop(now+delay+.17)})}catch(e){console.error(e)}}
function showOrderToast(o){document.querySelector(".order-toast")?.remove();const el=document.createElement("button");el.className="order-toast";el.innerHTML='<b>🔔 NEW '+(o.fulfillment_type==="delivery"?"DELIVERY":"PICKUP")+' ORDER</b><span>#'+esc(o.id.slice(0,8).toUpperCase())+' · '+money(o.total)+'</span>';el.onclick=()=>{ownerTab="orders";orderFilter=o.fulfillment_type==="delivery"?"delivery":"pickup";renderOwnerHub();el.remove()};document.body.appendChild(el);setTimeout(()=>el.remove(),10000)}
function renderOwnerHub(){const r=ownerRestaurant;if(!r)return;const app=document.querySelector("#ownerApp"),newCount=ownerOrders.filter(o=>o.status==="received").length;app.innerHTML='<div class="owner-top"><div class="owner-hub-nav"><button onclick="customerHome()">Home</button><button class="active" onclick="ownerNavigate(\'dashboard\')">Restaurant Dashboard</button></div><div class="owner-topline"><div><div class="owner-brand">Hoopa Eats · Restaurant</div><div class="owner-name">'+esc(r.name)+'</div></div><button class="status-pill '+(r.accepting_orders?'':'paused')+'" onclick="toggleOrders(\''+r.id+'\','+(!r.accepting_orders)+')">'+(r.accepting_orders?'● Accepting orders':'● Orders paused')+'</button></div></div></div>'+(localStorage.getItem("hoopaEatsSound")!=="on"?'<div class="sound-banner" id="soundEnable"><b>🔔 Order sound is off</b><button onclick="enableOrderSound()">Enable sound</button></div>':'')+'<div class="owner-content" id="ownerContent"></div><div class="owner-bottom"><button class="'+(ownerTab==="orders"?'active':'')+'" onclick="ownerNavigate(\'orders\')"><span class="nav-icon">🧾</span>Orders'+(newCount?'<span class="badge">'+newCount+'</span>':'')+'</button><button class="'+(ownerTab==="notifications"?'active':'')+'" onclick="ownerNavigate(\'notifications\')"><span class="nav-icon">🔔</span>Alerts</button><button class="'+(ownerTab==="payments"?'active':'')+'" onclick="ownerNavigate(\'payments\')"><span class="nav-icon">💳</span>Payments</button></div>';ownerNavigate(ownerTab)}
function ownerNavigate(tab){ownerTab=tab;document.querySelectorAll(".owner-bottom button").forEach((b,i)=>b.classList.toggle("active",["orders","notifications","payments"][i]===tab));if(tab==="dashboard")renderDashboard();if(tab==="orders")renderOrders();if(tab==="notifications")renderNotifications();if(tab==="payments")renderOwnerPayments();if(tab==="menu")renderOwnerMenu()}
function renderDashboard(){const r=ownerRestaurant,box=document.querySelector("#ownerContent");if(!box)return;box.innerHTML='<div class="owner-heading"><h1>Restaurant Dashboard</h1><button onclick="accountSettings()">⚙️ Account</button></div><div class="dashboard-grid"><button class="dash-card" onclick="ownerNavigate(\'orders\')"><b>🧾 Orders</b><span>Manage incoming pickup and delivery orders</span></button><button class="dash-card" onclick="ownerNavigate(\'menu\')"><b>🍔 Menu</b><span>Edit items, prices, categories and sold-out status</span></button><button class="dash-card" onclick="manageHours()"><b>🕐 Hours</b><span>Edit weekly restaurant hours</span></button><button class="dash-card" onclick="restaurantInfo()"><b>🏪 Restaurant info</b><span>Name, address, phone and pickup estimate</span></button><button class="dash-card" onclick="fulfillmentSettings()"><b>🚗 Pickup & delivery</b><span>Delivery fee, minimum and ordering options</span></button><button class="dash-card" onclick="toggleOrders(\''+r.id+'\','+(!r.accepting_orders)+')"><b>'+(r.accepting_orders?'⏸ Pause orders':'▶ Resume orders')+'</b><span>'+(r.accepting_orders?'Temporarily stop accepting new orders':'Start accepting new orders again')+'</span></button><button class="dash-card" onclick="menuPhotoInfo()"><b>📷 Upload menu photo</b><span>Import a restaurant menu from a photo</span></button><button class="dash-card" onclick="shareRestaurant()"><b>↗ Share restaurant</b><span>Share your Hoopa Eats restaurant page</span></button></div>'}
function restaurantInfo(){const r=ownerRestaurant;inside.innerHTML='<h2>Restaurant info</h2><input id="businessName" value="'+esc(r.name)+'" placeholder="Restaurant name"><textarea id="businessDescription" placeholder="Description">'+esc(r.description||"")+'</textarea><input id="businessPhone" value="'+esc(r.phone||"")+'" placeholder="Restaurant phone"><input id="businessAddress" value="'+esc(r.address||"")+'" placeholder="Restaurant address"><input id="pickupEstimate" type="number" min="5" max="180" value="'+Number(r.estimated_pickup_minutes||25)+'" placeholder="Estimated pickup minutes"><button class="primary full" onclick="saveBusinessSettings(\''+r.id+'\')">Save restaurant info</button>';sheet.showModal()}
function fulfillmentSettings(){const r=ownerRestaurant;inside.innerHTML='<h2>Pickup & delivery</h2><label><input id="offersPickup" type="checkbox" '+(r.offers_pickup!==false?'checked':'')+'> Pickup</label><br><label><input id="offersDelivery" type="checkbox" '+(r.offers_delivery?'checked':'')+'> Delivery</label><input id="deliveryFee" type="number" min="0" step="0.01" value="'+Number(r.delivery_fee||0)+'" placeholder="Delivery fee"><input id="deliveryMinimum" type="number" min="0" step="0.01" value="'+Number(r.delivery_minimum||0)+'" placeholder="Delivery minimum"><button class="primary full" onclick="saveFulfillment(\''+r.id+'\')">Save order options</button>';sheet.showModal()}
async function accountSettings(){const {data:{user}}=await db.auth.getUser();if(!user)return profile();const r=ownerRestaurant;inside.innerHTML='<div class="settings-page"><h2>Settings</h2><p class="muted">Manage your restaurant account and business information.</p><div class="settings-section"><h3>Account information</h3><label>Email<input id="settingsEmail" type="email" value="'+esc(user.email||"")+'" placeholder="Business email"></label><button class="primary full" onclick="updateAccountEmail()">Update email</button><button class="full" onclick="sendPasswordReset()">Reset password</button></div><div class="settings-section"><h3>Business information</h3><label>Restaurant name<input id="settingsBusinessName" value="'+esc(r?.name||"")+'" placeholder="Restaurant name"></label><label>Phone number<input id="settingsPhone" type="tel" value="'+esc(r?.phone||"")+'" placeholder="Restaurant phone"></label><label>Address<input id="settingsAddress" value="'+esc(r?.address||"")+'" placeholder="Restaurant address"></label><label>Description<textarea id="settingsDescription" placeholder="About your restaurant">'+esc(r?.description||"")+'</textarea></label><label>Estimated pickup time (minutes)<input id="settingsPickup" type="number" min="5" max="180" value="'+Number(r?.estimated_pickup_minutes||25)+'"></label><button class="primary full" onclick="saveAccountBusinessInfo()">Save business information</button></div><div class="settings-section"><h3>Subscription</h3><div class="settings-line"><div><b>Hoopa Eats restaurant plan</b><span>Subscription billing has not been activated yet.</span></div><span class="settings-chip">Not connected</span></div><button class="full" onclick="subscriptionSettings()">Manage subscription</button></div><div class="settings-section"><h3>Ordering</h3><button class="full" onclick="fulfillmentSettings()">Pickup & delivery settings</button><button class="full" onclick="manageHours()">Business hours</button></div><div class="settings-section"><h3>Account</h3><button class="danger full" onclick="logout()">Log out</button></div></div>';sheet.showModal()}
async function updateAccountEmail(){const input=document.querySelector("#settingsEmail"),email=input?.value.trim();if(!email)return alert("Enter an email address.");const {data:{user}}=await db.auth.getUser();if(email===user?.email)return alert("That is already your account email.");const {error}=await db.auth.updateUser({email});if(error)return alert(error.message);alert("Email update requested. Check your email to confirm the change.")}
async function sendPasswordReset(){const {data:{user}}=await db.auth.getUser();if(!user?.email)return alert("No account email found.");const {error}=await db.auth.resetPasswordForEmail(user.email,{redirectTo:location.origin});if(error)return alert(error.message);alert("Password reset email sent to "+user.email+".")}
async function saveAccountBusinessInfo(){if(!ownerRestaurant)return;const name=document.querySelector("#settingsBusinessName").value.trim(),phone=document.querySelector("#settingsPhone").value.trim(),address=document.querySelector("#settingsAddress").value.trim(),description=document.querySelector("#settingsDescription").value.trim(),mins=Math.max(5,Math.min(180,Number(document.querySelector("#settingsPickup").value)||25));if(!name)return alert("Enter your restaurant name.");const {data,error}=await db.from("restaurants").update({name,phone,address,description,estimated_pickup_minutes:mins}).eq("id",ownerRestaurant.id).select("*").single();if(error)return alert(error.message);ownerRestaurant=data;await loadRestaurants();alert("Business information saved.");accountSettings()}
function subscriptionSettings(){inside.innerHTML='<h2>Subscription</h2><div class="hub-panel"><b>Hoopa Eats restaurant plan</b><p class="muted">Subscription billing is not connected yet, so there is no charge to manage right now.</p></div><p>When billing is activated, this page will show the restaurant plan, billing status, renewal date, invoices, and controls to update or cancel the subscription.</p><button class="full" onclick="accountSettings()">Back to settings</button>';if(!sheet.open)sheet.showModal()}

function menuPhotoInfo(){inside.innerHTML='<h2>Upload menu photo</h2><p>Menu photo import needs secure file storage and menu extraction before it can safely publish changes.</p><p class="muted">For now, use the Menu tab to edit items directly. The upload control will be connected when storage/import is added.</p>';sheet.showModal()}
async function shareRestaurant(){const url=location.origin+'/?restaurant='+ownerRestaurant.id;if(navigator.share){try{return await navigator.share({title:ownerRestaurant.name,text:'Order from '+ownerRestaurant.name+' on Hoopa Eats',url})}catch(e){if(e.name==='AbortError')return}}inside.innerHTML='<h2>Share restaurant</h2><p>Copy this restaurant link:</p><input value="'+esc(url)+'" readonly>';sheet.showModal()}
function renderOrders(){const box=document.querySelector("#ownerContent");if(!box)return;const counts={all:ownerOrders.filter(o=>!["completed","cancelled"].includes(o.status)).length,pickup:ownerOrders.filter(o=>o.fulfillment_type!=="delivery"&&!["completed","cancelled"].includes(o.status)).length,delivery:ownerOrders.filter(o=>o.fulfillment_type==="delivery"&&!["completed","cancelled"].includes(o.status)).length};let list=ownerOrders.filter(o=>!["completed","cancelled"].includes(o.status));if(orderFilter==="pickup")list=list.filter(o=>o.fulfillment_type!=="delivery");if(orderFilter==="delivery")list=list.filter(o=>o.fulfillment_type==="delivery");box.innerHTML='<div class="owner-heading"><h1>Orders</h1><button onclick="ownerSettings()">⚙️</button></div><div class="owner-tabs"><button class="'+(orderFilter==="all"?'active':'')+'" onclick="setOrderFilter(\'all\')">All '+counts.all+'</button><button class="'+(orderFilter==="pickup"?'active':'')+'" onclick="setOrderFilter(\'pickup\')">🏪 Pickup '+counts.pickup+'</button><button class="'+(orderFilter==="delivery"?'active':'')+'" onclick="setOrderFilter(\'delivery\')">🚗 Delivery '+counts.delivery+'</button></div>'+(list.length?list.map(orderCard).join(""):'<div class="empty-state"><h2>All caught up</h2><p>No active '+(orderFilter==="all"?'':orderFilter+' ')+'orders right now.</p></div>')}
function setOrderFilter(v){orderFilter=v;renderOrders()}
function orderCard(o){const items=o.order_items||[],action={received:"Accept order",accepted:"Start preparing",preparing:"Almost ready",almost_ready:"Mark ready",ready:"Complete"}[o.status],time=new Date(o.created_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}),type=o.fulfillment_type==="delivery"?"🚗 Delivery":"🏪 Pickup";return '<article class="order-card '+(o.status==="received"?'new':'')+'"><div class="order-meta"><div><div class="order-number">#'+esc(o.id.slice(0,8).toUpperCase())+'</div><span class="order-type">'+type+' · '+esc(o.status.replace("_"," "))+'</span></div><b>'+esc(time)+'</b></div><div class="order-items">'+(items.length?items.map(i=>'<div class="order-line"><span><b>'+i.quantity+'×</b> '+esc(i.item_name)+'</span><span>'+money(Number(i.unit_price)*Number(i.quantity))+'</span></div>').join(""):'<span class="muted">Item details unavailable</span>')+'</div><div class="order-line"><span>'+esc(o.customer_name)+(o.customer_phone?'<br><span class="muted">'+esc(o.customer_phone)+'</span>':'')+'</span><span class="order-total">'+money(o.total)+'</span></div>'+(o.fulfillment_type==="delivery"&&o.delivery_address?'<p><b>Deliver to:</b> '+esc(o.delivery_address)+'</p>':'')+(o.delivery_instructions?'<p class="muted">📝 '+esc(o.delivery_instructions)+'</p>':'')+(o.customer_notes?'<p class="muted">📝 '+esc(o.customer_notes)+'</p>':'')+'<div class="order-actions">'+(action?'<button class="primary" onclick="advanceOrder(\''+o.id+'\',\''+o.status+'\')">'+action+'</button>':'')+(o.status!=="completed"?'<button class="danger" onclick="cancelOrder(\''+o.id+'\')">Cancel</button>':'')+'</div></article>'}
function renderNotifications(){const box=document.querySelector("#ownerContent"),recent=ownerOrders.filter(o=>o.status==="received");box.innerHTML='<div class="owner-heading"><h1>Notifications</h1><button onclick="ownerSettings()">⚙️</button></div>'+(recent.length?recent.map(o=>'<div class="hub-panel"><b>New '+(o.fulfillment_type==="delivery"?'delivery':'pickup')+' order</b><p>#'+esc(o.id.slice(0,8).toUpperCase())+' · '+esc(o.customer_name)+' · '+money(o.total)+'</p><button onclick="ownerNavigate(\'orders\')">View order</button></div>').join(""):'<div class="empty-state"><h2>No new alerts</h2><p>New-order notifications will show here.</p></div>')}
let paymentView="sales";
function renderOwnerPayments(){const box=document.querySelector("#ownerContent");if(!box)return;const paid=ownerOrders.filter(o=>o.payment_status==="paid"),pending=ownerOrders.filter(o=>o.payment_status==="pending"),refunded=ownerOrders.filter(o=>o.payment_status==="refunded"),cancelled=ownerOrders.filter(o=>o.status==="cancelled"),paidTotal=paid.reduce((s,o)=>s+Number(o.total||0),0),today=new Date().toDateString(),todayPaid=paid.filter(o=>new Date(o.created_at).toDateString()===today),todayTotal=todayPaid.reduce((s,o)=>s+Number(o.total||0),0);box.innerHTML='<div class="owner-heading"><h1>Payments</h1><button onclick="ownerSettings()">⚙️</button></div><div class="payment-tabs"><button class="'+(paymentView==="sales"?"active":"")+'" onclick="setPaymentView(\'sales\')">Sales</button><button class="'+(paymentView==="transactions"?"active":"")+'" onclick="setPaymentView(\'transactions\')">Transactions</button><button class="'+(paymentView==="refunds"?"active":"")+'" onclick="setPaymentView(\'refunds\')">Refunds / Cancellations</button><button class="'+(paymentView==="payouts"?"active":"")+'" onclick="setPaymentView(\'payouts\')">Payouts</button></div><div id="paymentPanel"></div>';renderPaymentPanel({paid,pending,refunded,cancelled,paidTotal,todayPaid,todayTotal})}
function setPaymentView(v){paymentView=v;renderOwnerPayments()}
function paymentRow(o){return '<div class="payment-row"><div><b>#'+esc(o.id.slice(0,8).toUpperCase())+'</b><span>'+esc(o.customer_name||"Guest")+' · '+new Date(o.created_at).toLocaleDateString()+'</span></div><div class="payment-amount"><b>'+money(o.total)+'</b><span class="pay-status '+esc(o.payment_status||"unpaid")+'">'+esc(o.payment_status||"unpaid")+'</span></div></div>'}
function renderPaymentPanel(d){const box=document.querySelector("#paymentPanel");if(!box)return;if(paymentView==="sales"){box.innerHTML='<div class="payment-stats"><div><span>Today</span><b>'+money(d.todayTotal)+'</b><small>'+d.todayPaid.length+' paid orders</small></div><div><span>Total paid</span><b>'+money(d.paidTotal)+'</b><small>'+d.paid.length+' orders</small></div><div><span>Pending</span><b>'+d.pending.length+'</b><small>payments</small></div></div><div class="hub-panel"><h3>Recent paid sales</h3>'+(d.paid.length?d.paid.slice(0,20).map(paymentRow).join(""):'<p class="muted">No paid sales yet.</p>')+'</div>';return}if(paymentView==="transactions"){box.innerHTML='<div class="hub-panel"><h3>Transactions</h3><p class="muted">Every Hoopa Eats order and its current payment status.</p>'+(ownerOrders.length?ownerOrders.slice(0,50).map(paymentRow).join(""):'<p class="muted">No transactions yet.</p>')+'</div>';return}if(paymentView==="refunds"){const rows=[...d.cancelled,...d.refunded.filter(r=>!d.cancelled.some(c=>c.id===r.id))];box.innerHTML='<div class="hub-panel"><h3>Refunds & cancellations</h3><p class="muted">Cancelled and refunded orders are tracked here. Automatic money refunds require the payment processor connection.</p>'+(rows.length?rows.map(o=>'<div class="payment-row"><div><b>#'+esc(o.id.slice(0,8).toUpperCase())+'</b><span>'+esc(o.customer_name||"Guest")+' · '+esc(o.status)+'</span></div><div class="payment-amount"><b>'+money(o.total)+'</b><span class="pay-status '+esc(o.payment_status||"unpaid")+'">'+esc(o.payment_status||"unpaid")+'</span></div></div>').join(""):'<p class="muted">No cancellations or refunds.</p>')+'</div>';return}box.innerHTML='<div class="hub-panel"><h3>Payouts</h3><p class="muted">Payout tracking will activate when Hoopa Eats connects a marketplace payment processor and the restaurant connects its payout account.</p><div class="payout-preview"><span>Available to track</span><b>'+money(d.paidTotal)+'</b><small>Paid order volume — not a bank balance or payout amount.</small></div></div>'}

async function renderOwnerMenu(){const box=document.querySelector("#ownerContent");box.innerHTML='<div class="owner-heading"><h1>Menu</h1><button onclick="ownerSettings()">⚙️</button></div><p>Loading menu…</p>';const {data:items,error}=await db.from("menu_items").select("*").eq("restaurant_id",ownerRestaurant.id).order("created_at");if(error)return box.innerHTML='<p>Menu could not load.</p>';box.innerHTML='<div class="owner-heading"><h1>Edit menu items</h1><button onclick="ownerSettings()">⚙️</button></div><p class="muted">Tap Edit to change an item, price, category, description, or sold-out status.</p><div class="hub-panel">'+((items||[]).map(x=>'<div class="menu row"><div><b>'+esc(x.name)+'</b><br><span class="muted">'+esc(x.category||"Uncategorized")+'</span><br>'+money(x.price)+(x.is_available?'':' · <b>Sold out</b>')+'</div><button onclick="editMenuItem(\''+x.id+'\')">Edit</button></div>').join("")||'<p>No menu items yet.</p>')+'</div><button class="primary full" onclick="newMenuItem()">+ New menu item</button>'}
async function editMenuItem(id){const {data:x,error}=await db.from("menu_items").select("*").eq("id",id).single();if(error)return alert(error.message);menuItemForm(x)}
function newMenuItem(){menuItemForm({id:null,name:"",description:"",price:"",category:"",is_available:true})}
function menuItemForm(x){inside.innerHTML='<h2>'+(x.id?'Edit menu item':'New menu item')+'</h2><label>Item name<input id="editItemName" value="'+esc(x.name||"")+'" placeholder="Example: Cheeseburger"></label><label>Description<textarea id="editItemDescription" placeholder="Describe the item">'+esc(x.description||"")+'</textarea></label><label>Category<input id="editItemCategory" value="'+esc(x.category||"")+'" placeholder="Burgers, Breakfast, Drinks, etc."></label><label>Price<input id="editItemPrice" type="number" min="0" step="0.01" value="'+esc(x.price??"")+'" placeholder="0.00"></label><label><input id="editItemAvailable" type="checkbox" '+(x.is_available!==false?'checked':'')+'> Available for ordering</label><p class="muted">Turn this off to mark the item Sold out without deleting it.</p><button class="primary full" onclick="saveMenuItem('+(x.id?'\''+x.id+'\'':'null')+')">Save item</button>'+(x.id?'<button class="danger full" onclick="deleteMenuItem(\''+x.id+'\')">Delete item</button>':'')+'<button class="full" onclick="sheet.close();ownerNavigate(\'menu\')">Back to menu</button>';sheet.showModal()}
async function saveMenuItem(id){const name=document.querySelector("#editItemName").value.trim(),description=document.querySelector("#editItemDescription").value.trim(),category=document.querySelector("#editItemCategory").value.trim(),price=Number(document.querySelector("#editItemPrice").value),is_available=document.querySelector("#editItemAvailable").checked;if(!name)return alert("Enter an item name.");if(!Number.isFinite(price)||price<0)return alert("Enter a valid price.");const values={restaurant_id:ownerRestaurant.id,name,description,category:category||null,price,is_available};const q=id?db.from("menu_items").update(values).eq("id",id):db.from("menu_items").insert(values),{error}=await q;if(error)return alert(error.message);sheet.close();renderOwnerMenu()}
async function deleteMenuItem(id){if(!confirm("Delete this menu item? Existing orders will keep their saved item details."))return;const {error}=await db.from("menu_items").delete().eq("id",id);if(error)return alert(error.message);sheet.close();renderOwnerMenu()}
function ownerSettings(){return accountSettings()}
function legacyOwnerSettings(){const r=ownerRestaurant;inside.innerHTML='<h2>Restaurant dashboard</h2><div class="hub-panel"><h3>Business</h3><input id="businessName" value="'+esc(r.name)+'" placeholder="Restaurant name"><textarea id="businessDescription" placeholder="Description">'+esc(r.description||"")+'</textarea><input id="businessPhone" value="'+esc(r.phone||"")+'" placeholder="Restaurant phone"><input id="businessAddress" value="'+esc(r.address||"")+'" placeholder="Restaurant address"><input id="pickupEstimate" type="number" min="5" max="180" value="'+Number(r.estimated_pickup_minutes||25)+'" placeholder="Estimated pickup minutes"><button class="primary full" onclick="saveBusinessSettings(\''+r.id+'\')">Save business info</button></div><div class="hub-panel"><h3>Pickup & delivery</h3><label><input id="offersPickup" type="checkbox" '+(r.offers_pickup!==false?'checked':'')+'> Pickup</label><br><label><input id="offersDelivery" type="checkbox" '+(r.offers_delivery?'checked':'')+'> Delivery</label><input id="deliveryFee" type="number" min="0" step="0.01" value="'+Number(r.delivery_fee||0)+'" placeholder="Delivery fee"><input id="deliveryMinimum" type="number" min="0" step="0.01" value="'+Number(r.delivery_minimum||0)+'" placeholder="Delivery minimum"><button class="primary full" onclick="saveFulfillment(\''+r.id+'\')">Save order options</button></div><div class="hub-panel"><h3>Business hours</h3><p class="muted">Set the hours customers can order. You can still pause new orders anytime.</p><button class="full" onclick="manageHours()">Edit weekly hours</button></div><button class="full" onclick="logout()">Log out</button>';sheet.showModal()}
async function saveBusinessSettings(id){const mins=Math.max(5,Math.min(180,Number(document.querySelector("#pickupEstimate").value)||25));const {error}=await db.from("restaurants").update({name:document.querySelector("#businessName").value.trim(),description:document.querySelector("#businessDescription").value.trim(),phone:document.querySelector("#businessPhone").value.trim(),address:document.querySelector("#businessAddress").value.trim(),estimated_pickup_minutes:mins}).eq("id",id);if(error)return alert(error.message);await loadRestaurants();await ownerDashboard();alert("Business info saved.")}
async function manageHours(){const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],{data,error}=await db.from("restaurant_hours").select("*").eq("restaurant_id",ownerRestaurant.id);if(error)return alert(error.message);const byDay=Object.fromEntries((data||[]).map(x=>[x.day_of_week,x]));inside.innerHTML='<h2>Weekly hours</h2><p class="muted">These are the restaurant’s ordering hours.</p>'+days.map((d,i)=>{const h=byDay[i];return '<div class="hours-row"><label><input class="day-closed" data-day="'+i+'" type="checkbox" '+(h?.is_closed?'checked':'')+'> '+d+' closed</label><div class="hours-times"><input class="day-open" data-day="'+i+'" type="time" value="'+esc(h?.open_time?.slice(0,5)||"10:30")+'"><span>to</span><input class="day-close" data-day="'+i+'" type="time" value="'+esc(h?.close_time?.slice(0,5)||"18:00")+'"></div></div>'}).join("")+'<button class="primary full" onclick="saveHours()">Save weekly hours</button><button class="full" onclick="ownerSettings()">Back to dashboard</button>';sheet.showModal()}
async function saveHours(){const rows=[...document.querySelectorAll(".day-closed")].map(c=>{const day=Number(c.dataset.day),open=document.querySelector('.day-open[data-day="'+day+'"]').value,close=document.querySelector('.day-close[data-day="'+day+'"]').value;return {restaurant_id:ownerRestaurant.id,day_of_week:day,is_closed:c.checked,open_time:c.checked?null:open,close_time:c.checked?null:close}});for(const row of rows){const {error}=await db.from("restaurant_hours").upsert(row,{onConflict:"restaurant_id,day_of_week"});if(error)return alert(error.message)}alert("Weekly hours saved.");ownerSettings()}
async function cancelOrder(id){if(!confirm("Cancel this order?"))return;const {error}=await db.from("orders").update({status:"cancelled"}).eq("id",id);if(error)return alert(error.message);ownerDashboard()}
async function createRestaurant(){const {data:{user}}=await db.auth.getUser();if(!rname.value.trim())return alert("Enter restaurant name.");const {error}=await db.from("restaurants").insert({owner_id:user.id,name:rname.value.trim(),description:rdesc.value.trim()});if(error)return alert(error.message);await loadRestaurants();ownerDashboard()}
async function toggleOrders(id,v){const {error}=await db.from("restaurants").update({accepting_orders:v}).eq("id",id);if(error)return alert(error.message);await loadRestaurants();ownerDashboard()}
async function saveFulfillment(id){const p=document.querySelector("#offersPickup").checked,d=document.querySelector("#offersDelivery").checked;if(!p&&!d)return alert("Keep Pickup or Delivery enabled so customers have a way to order.");const {error}=await db.from("restaurants").update({offers_pickup:p,offers_delivery:d,delivery_fee:Math.max(0,Number(document.querySelector("#deliveryFee").value)||0),delivery_minimum:Math.max(0,Number(document.querySelector("#deliveryMinimum").value)||0)}).eq("id",id);if(error)return alert(error.message);sheet.close();await loadRestaurants();ownerDashboard()}
const flow=["received","accepted","preparing","almost_ready","ready","completed"];
async function advanceOrder(id,s){const i=flow.indexOf(s);if(i<0||i===flow.length-1)return;const {error}=await db.from("orders").update({status:flow[i+1]}).eq("id",id);if(error)return alert(error.message);ownerDashboard()}
async function manageMenu(rid){const {data:items}=await db.from("menu_items").select("*").eq("restaurant_id",rid).order("created_at");inside.innerHTML='<h2>Manage menu</h2>'+((items||[]).map(x=>'<div class="menu row"><div><b>'+esc(x.name)+'</b><br>'+money(x.price)+'</div><button onclick="toggleItem(\''+x.id+'\','+(!x.is_available)+',\''+rid+'\')">'+(x.is_available?"Sold out":"Available")+'</button></div>').join("")||'<p>No menu items yet.</p>')+'<h3>Add item</h3><input id="iname" placeholder="Item name"><input id="iprice" type="number" step="0.01" placeholder="Price"><textarea id="idesc" placeholder="Description"></textarea><button class="primary full" onclick="addMenuItem(\''+rid+'\')">Add item</button>'}
async function addMenuItem(rid){const p=Number(iprice.value);if(!iname.value.trim()||!Number.isFinite(p))return alert("Enter item name and price.");const {error}=await db.from("menu_items").insert({restaurant_id:rid,name:iname.value.trim(),price:p,description:idesc.value.trim()});if(error)return alert(error.message);await loadRestaurants();manageMenu(rid)}
async function toggleItem(id,v,rid){const {error}=await db.from("menu_items").update({is_available:v}).eq("id",id);if(error)return alert(error.message);manageMenu(rid)}
async function logout(){if(orderChannel){db.removeChannel(orderChannel);orderChannel=null}await db.auth.signOut();ownerRestaurant=null;ownerOrders=[];document.querySelector("#ownerApp").hidden=true;document.querySelector("#customerApp").hidden=false;sheet.close();inside.innerHTML="<h2>Logged out</h2>";refreshDashboardTab()}
function payments(){inside.innerHTML="<h2>Payments</h2><p class=\"muted\">Online payments are not connected yet.</p><div class=\"hub-panel\"><b>Pay for Hoopa Eats orders</b><p>When secure online payments are connected, this is where customers will manage payment options and view payment status.</p></div><p class=\"muted\">For your security, do not enter card information anywhere on Hoopa Eats yet.</p><button class=\"full\" onclick=\"sheet.close()\">Close</button>";sheet.showModal()}
function home(){customerHome()}
loadRestaurants();